name: Build Zmicro Docker Image

image: whatwewant/zmicro:v1

environment:
  CI: "true"
  EUNOMIA_BUILD_ID: "10000"
  EUNOMIA_BUILD_TIMESTAMP: "1727070237"
  EUNOMIA_CI: "true"
  EUNOMIA_GIT_BRANCH: master
  EUNOMIA_GIT_REPOSITORY: https://github.com/go-idp/pipeline
  EUNOMIA_NAME: "Build Zmicro Docker Image"
  EUNOMIA_RUNNER_ARCH: amd64
  EUNOMIA_RUNNER_NAME: Eunomia CI
  EUNOMIA_RUNNER_OS: Linux
  EUNOMIA_RUNNER_PLATFORM: linux
  EUNOMIA_RUNNER_USER: runner

stages:
  - name: checkout
    jobs:
      - name: checkout
        steps:
          - name: checkout
            command: |
              echo "[$(date))] checkout"
              pwd
              ls -al
              # git clone --progress --depth 1 -b ${EUNOMIA_GIT_BRANCH} ${EUNOMIA_GIT_REPOSITORY} $PWD
              
  - name: build
    jobs:
      - name: build
        steps:
          - name: build
            command: |
              echo "[$(date))] build"
              pwd
              ls -al

  - name: deploy
    type: deploy
    mode: serial 
    title: deploy
    jobs:
      - name: deploy
        steps:
          - name: deploy
            command: |
              echo "[$(date))] deploy"
              pwd
              ls -al


