name: Build Zmicro Docker Image

environment:
  CI: "true"
  EUNOMIA_BUILD_ID: "10000"
  EUNOMIA_BUILD_TIMESTAMP: "1727070237"
  EUNOMIA_CI: "true"
  EUNOMIA_GIT_BRANCH: master
  EUNOMIA_GIT_REPOSITORY: https://github.com/go-idp/pipeline
  EUNOMIA_NAME: "Build Zmicro Docker Image"
  EUNOMIA_RUNNER_ARCH: amd64
  EUNOMIA_RUNNER_NAME: Eunomia CI
  EUNOMIA_RUNNER_OS: Linux
  EUNOMIA_RUNNER_PLATFORM: linux
  EUNOMIA_RUNNER_USER: runner

stages:
  - name: checkout
    jobs:
      - name: frontend
        steps:
          - name: checkout
            command: |
              console.log(`[$(new Date())] run with nodejs`)
              # echo "BAS64_STRING" | base64 -d > /tmp/script
              # node /tmp/script
            language: 
              name: node
              version: 16


