name: Build Zmicro Docker Image

environment:
  CI: "true"
  EUNOMIA_BUILD_ID: "10000"
  EUNOMIA_BUILD_TIMESTAMP: "1727070237"
  EUNOMIA_CI: "true"
  EUNOMIA_GIT_BRANCH: master
  EUNOMIA_GIT_REPOSITORY: https://github.com/go-idp/pipeline
  EUNOMIA_NAME: "Build Zmicro Docker Image"
  EUNOMIA_RUNNER_ARCH: amd64
  EUNOMIA_RUNNER_NAME: Eunomia CI
  EUNOMIA_RUNNER_OS: Linux
  EUNOMIA_RUNNER_PLATFORM: linux
  EUNOMIA_RUNNER_USER: runner

stages:
  - name: checkout
    jobs:
      - name: frontend
        steps:
          - name: checkout
            plugin: 
              # image: pipeline/checkout:v1 # call cmd => /pipeline/plugin/run
              # settings:
              #   username: "username"
              #   token: "token"
              #   repository: ${EUNOMIA_GIT_REPOSITORY}
              image: docker.io/library/busybox:latest
              settings:
                username: "test"
                token: "test"
                repository: https://github.com/go-idp/pipeline
                test_env: ${EUNOMIA_RUNNER_OS}
              # entrypoint: /bin/date
              entrypoint: /bin/env
              
  - name: build
    jobs:
      - name: build
        steps:
          - name: build
            command: |
              echo "[$(date))] build"

  - name: deploy
    type: deploy
    mode: serial 
    title: deploy
    jobs:
      - name: deploy
        steps:
          - name: deploy
            command: |
              echo "[$(date))] deploy"


