name: Build Zmicro Docker Image

environment:
  CI: "true"
  EUNOMIA_BUILD_ID: "10000"
  EUNOMIA_BUILD_TIMESTAMP: "1727070237"
  EUNOMIA_CI: "true"
  EUNOMIA_GIT_BRANCH: master
  EUNOMIA_GIT_REPOSITORY: https://github.com/go-idp/pipeline
  EUNOMIA_NAME: "Build Zmicro Docker Image"
  EUNOMIA_RUNNER_ARCH: amd64
  EUNOMIA_RUNNER_NAME: Eunomia CI
  EUNOMIA_RUNNER_OS: Linux
  EUNOMIA_RUNNER_PLATFORM: linux
  EUNOMIA_RUNNER_USER: runner

stages:
  - name: checkout
    jobs:
      - name: frontend
        steps:
          - name: checkout
            plugin: 
              # image: pipeline/build:v1 # call cmd => /pipeline/plugin/run
              image: docker.io/library/busybox:latest
              settings:
                context: . # PIPELINE_PLUGIN_SETTINGS_CONTEXT
                tags: registry.idp.example.com/idp/backend:test-pipeline
              entrypoint: /bin/date

              
  - name: build
    jobs:
      - name: build
        steps:
          - name: build
            command: |
              echo "[$(date))] build"

  - name: deploy
    type: deploy
    mode: serial 
    title: deploy
    jobs:
      - name: deploy
        steps:
          - name: deploy
            command: |
              echo "[$(date))] deploy"


