name: examples/step-engine-ssh

stages:
  - name: build
    jobs:
      - name: 构建
        steps:
          - name: build
            engine: ssh://user:pass@10.0.0.2:22
            command: |
              echo "[$(date))] build in agent"
              hostname
